version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=EventEvonik
      - POSTGRES_PASSWORD=EventEvonik1213
      - POSTGRES_DB=EventEvonik
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

